name: Docker Deployment

on:
  push:
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Process tag name
        id: tag
        run: |
          # Remove 'v' prefix from tag name
          TAG_NAME=${GITHUB_REF#refs/tags/v}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      
      - name: Build and push Docker image for filesystem
        uses: docker/build-push-action@v5
        with:
          file: ./src/filesystem/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/filesystem:${{ steps.tag.outputs.TAG_NAME }}
            ${{ secrets.DOCKER_USERNAME }}/filesystem:latest

      - name: Build and push Docker image for sequential thinking
        uses: docker/build-push-action@v5
        with:
          file: ./src/sequentialthinking/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sequentialthinking:${{ steps.tag.outputs.TAG_NAME }}
            ${{ secrets.DOCKER_USERNAME }}/sequentialthinking:latest
